@MerkleTreeApi_HostAddress = http://localhost:5296

POST {{MerkleTreeApi_HostAddress}}/api/userbalance/create
Accept: application/json

POST {{MerkleTreeApi_HostAddress}}/api/userbalance/getbalance
Accept: application/json

###
